"""add current_ledger_id to users table

Revision ID: 458fbd4e8913
Revises: 81d3c1b87591
Create Date: 2025-07-12 02:09:55.752578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458fbd4e8913'
down_revision: Union[str, None] = '81d3c1b87591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_ledger_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'ledgers', ['current_ledger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_ledger_id')
    # ### end Alembic commands ###
